package com.lakedev.KnowledgeBase.model;
// Generated Mar 5, 2019 4:10:23 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SavedFile generated by hbm2java
 */
@Entity
@Table(name = "saved_file", uniqueConstraints = @UniqueConstraint(columnNames = "file_name"))
public class SavedFile implements java.io.Serializable
{
	private static final long serialVersionUID = -4824477966158105986L;
	private int fileId;
	private String fileName;
	private byte[] fileData;

	public SavedFile()
	{
	}

	public SavedFile(int fileId, String fileName, byte[] fileData)
	{
		this.fileId = fileId;
		this.fileName = fileName;
		this.fileData = fileData;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "file_id", unique = true, nullable = false)
	public int getFileId()
	{
		return this.fileId;
	}

	public void setFileId(int fileId)
	{
		this.fileId = fileId;
	}

	@Column(name = "file_name", unique = true, nullable = false, length = 2000000000)
	public String getFileName()
	{
		return this.fileName;
	}

	public void setFileName(String fileName)
	{
		this.fileName = fileName;
	}

	@Column(name = "file_data", nullable = false, length = 2000000000)
	public byte[] getFileData()
	{
		return this.fileData;
	}

	public void setFileData(byte[] fileData)
	{
		this.fileData = fileData;
	}

}
