package com.lakedev.KnowledgeBase.model;
// Generated Feb 21, 2019 3:29:32 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.springframework.data.domain.Persistable;

/**
 * SavedNote generated by hbm2java
 */
@Entity
@Table(name = "saved_note", uniqueConstraints = @UniqueConstraint(columnNames = "note_text"))
public class SavedNote implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 3433350195732066285L;
	private int noteId = -1;
	private String noteTitle;
	private String noteText;

	public SavedNote()
	{
	}

	public SavedNote(int noteId, String noteTitle, String noteText)
	{
		this.noteId = noteId;
		this.noteTitle = noteTitle;
		this.noteText = noteText;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "note_id", unique = true, nullable = false)
	public int getNoteId()
	{
		return this.noteId;
	}

	public void setNoteId(int noteId)
	{
		this.noteId = noteId;
	}

	@Column(name = "note_title", nullable = false, length = 2000000000)
	public String getNoteTitle()
	{
		return this.noteTitle;
	}

	public void setNoteTitle(String noteTitle)
	{
		this.noteTitle = noteTitle;
	}

	@Column(name = "note_text", unique = true, nullable = false, length = 2000000000)
	public String getNoteText()
	{
		return this.noteText;
	}

	public void setNoteText(String noteText)
	{
		this.noteText = noteText;
	}

}
