package com.lakedev.KnowledgeBase.model;
// Generated Mar 5, 2019 4:10:23 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "task")
public class Task implements java.io.Serializable
{

	private static final long serialVersionUID = -8575079531428062266L;
	private int id;
	private String text;
	private int complete;

	public Task()
	{
	}

	public Task(int id, String text, int complete)
	{
		this.id = id;
		this.text = text;
		this.complete = complete;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "text", nullable = false, length = 2000000000)
	public String getText()
	{
		return this.text;
	}

	public void setText(String text)
	{
		this.text = text;
	}
	
	@Column(name = "complete", nullable = false)
	public int getComplete()
	{
		return this.complete;
	}
	
	public void setComplete(int complete)
	{
		this.complete = complete;
	}

}
