package com.lakedev.KnowledgeBase.model;
// Generated Mar 5, 2019 4:10:23 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TodoListTask generated by hbm2java
 */
@Entity
@Table(name = "todo_list_task")
public class TodoListTask implements java.io.Serializable
{

	private static final long serialVersionUID = 8978634077477919509L;
	private int id;
	private TodoList todoList;
	private Task task;

	public TodoListTask()
	{
	}

	public TodoListTask(int id, TodoList todoList, Task task)
	{
		this.id = id;
		this.todoList = todoList;
		this.task = task;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "todo_list", nullable = false)
	public TodoList getTodoList()
	{
		return this.todoList;
	}

	public void setTodoList(TodoList todoList)
	{
		this.todoList = todoList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "task", nullable = false)
	public Task getTask()
	{
		return this.task;
	}

	public void setTask(Task task)
	{
		this.task = task;
	}

}
