package com.lakedev.KnowledgeBase.model;
// Generated Mar 5, 2019 4:10:23 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TodoList generated by hbm2java
 */
@Entity
@Table(name = "todo_list", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class TodoList implements java.io.Serializable
{

	private int id;
	private String name;
	private Set<TodoListTask> todoListTasks = new HashSet<TodoListTask>(0);

	public TodoList()
	{
	}

	public TodoList(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public TodoList(int id, String name, Set<TodoListTask> todoListTasks)
	{
		this.id = id;
		this.name = name;
		this.todoListTasks = todoListTasks;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 2000000000)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "todoList")
	public Set<TodoListTask> getTodoListTasks()
	{
		return this.todoListTasks;
	}

	public void setTodoListTasks(Set<TodoListTask> todoListTasks)
	{
		this.todoListTasks = todoListTasks;
	}

}
